### ISSUE TITLE
Arrows/Connections remain visible

### ISSUE THREAD

**Issue by boyen-cell** [IKoshelev/Obsidian-Canvas-Filter#7]
The plugin is really useful to me, but one problem I have is that when I filter items then it hides the notes and cards exactly as it should, but it leaves the arrows/connectors visible which still makes the canvas feel cluttered.

![image](https://github.com/IKoshelev/Obsidian-Canvas-Filter/assets/29734238/9d2ffbbb-bd59-4a00-b8d1-16b4beee68b6)

**Comment by brine0m** [comment]
I am also getting the exact same issue as displayed.

**Comment by Murgeye** [comment]
Same issue as reported in #6 .

**Comment by Gentleman03** [comment]
I confirm, unfortunately plugin doesn't behave like it supposed to. I hope it will be fixed because it's the only plugin of this kind. 
@IKoshelev could you let us know if you'll be able to fix your plugin soon? Please :)
